name: 'Hello World'

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

jobs:
  ci-cd:
    runs-on: ubuntu-latest
    steps:   
      - uses: actions/checkout@v3
      - name: docker-build
        run: docker build -t teste .
